DROP TABLE IF EXISTS param_ensemble;
CREATE TABLE param_ensemble (id PRIMARY KEY UNIQUE NOT NULL, net_arch TEXT, dataset TEXT, esb_type TEXT, esb_size INTEGER);
INSERT INTO param_ensemble (id, net_arch, dataset, esb_type, esb_size) VALUES (1, 'DenseNet', 'CIFAR-10', 'horizontal', 8);
INSERT INTO param_ensemble (id, net_arch, dataset, esb_type, esb_size) VALUES (2, 'DenseNet', 'CIFAR-10', 'horizontal', 4);
INSERT INTO param_ensemble (id, net_arch, dataset, esb_type, esb_size) VALUES (3, 'resnet', 'cifar100', 'horizontal', 4);
INSERT INTO param_ensemble (id, net_arch, dataset, esb_type, esb_size) VALUES (4, 'vgg', 'cifar10', 'horizontal', 4);
INSERT INTO param_ensemble (id, net_arch, dataset, esb_type, esb_size) VALUES (5, 'resnet', 'cifar10', 'horizontal', 6);
INSERT INTO param_ensemble (id, net_arch, dataset, esb_type, esb_size) VALUES (6, 'vgg', 'cifar10', 'vertical', 4);
INSERT INTO param_ensemble (id, net_arch, dataset, esb_type, esb_size) VALUES (7, 'wrn', 'cifar10', 'horizontal', 4);
INSERT INTO param_ensemble (id, net_arch, dataset, esb_type, esb_size) VALUES (8, 'DenseNet', 'CIFAR-100', 'vertical', 4);
INSERT INTO param_ensemble (id, net_arch, dataset, esb_type, esb_size) VALUES (9, 'resnet', 'cifar10', 'vertical', 6);
INSERT INTO param_ensemble (id, net_arch, dataset, esb_type, esb_size) VALUES (10, 'DenseNet', 'CIFAR-10', 'vertical', 4);
INSERT INTO param_ensemble (id, net_arch, dataset, esb_type, esb_size) VALUES (11, 'wrn', 'cifar10', 'vertical', 4);
INSERT INTO param_ensemble (id, net_arch, dataset, esb_type, esb_size) VALUES (12, 'DenseNet', 'CIFAR-10', 'vertical', 8);
INSERT INTO param_ensemble (id, net_arch, dataset, esb_type, esb_size) VALUES (13, 'resnet', 'cifar10', 'vertical', 8);
INSERT INTO param_ensemble (id, net_arch, dataset, esb_type, esb_size) VALUES (14, 'resnet', 'cifar10', 'vertical', 4);
INSERT INTO param_ensemble (id, net_arch, dataset, esb_type, esb_size) VALUES (15, 'DenseNet', 'CIFAR-10', 'vertical', 6);
INSERT INTO param_ensemble (id, net_arch, dataset, esb_type, esb_size) VALUES (16, 'DenseNet', 'CIFAR-10', 'horizontal', 6);
INSERT INTO param_ensemble (id, net_arch, dataset, esb_type, esb_size) VALUES (17, 'resnet', 'cifar100', 'vertical', 4);
INSERT INTO param_ensemble (id, net_arch, dataset, esb_type, esb_size) VALUES (18, 'resnet', 'cifar10', 'horizontal', 8);
INSERT INTO param_ensemble (id, net_arch, dataset, esb_type, esb_size) VALUES (19, 'DenseNet', 'CIFAR-100', 'horizontal', 4);
INSERT INTO param_ensemble (id, net_arch, dataset, esb_type, esb_size) VALUES (20, 'resnet', 'cifar10', 'horizontal', 4);
